before_commands:
    - "composer install --no-dev --prefer-source"

tools:
    external_code_coverage:
        timeout: 1200
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "testing/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "examples", "testing/Tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "testing/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs", "examples", "testing/Tests", "vendor"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs", "examples", "testing/Tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "testing/*"]
    sensiolabs_security_checker: true
